name: Coverage
on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'
      - name: Running tests
        run: |
          pip install pipenv
          pipenv install --dev
          coverage run pipenv run tests
          coverage xml --include='./monero_usd_price/**'
      - name: Get Coverage
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 1
