name: Run Ruff Linter
run-name: Linting the project
on: [push]
jobs:
  Ruff-Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Running ruff linter
        run: |
          pip install ruff
          ruff check .
